### ISSUE TITLE
POST Request for API

### ISSUE THREAD

**Issue by RuyokiVenyl** [Breadisfunie/Termbot#1]
How would this API function to retrieve the "url"? I think I'm overanalyzing how Roblox employs captchas, also called FunCaptchas, which are created by Arkose Labs. Since Roblox requests aren't monitored, I don't think you can POST requests to Gmail. Given that it requires captchas, email addresses, and other information based on the Roblox illegal content reporting system, I'm not sure how this will operate.

**Comment by RuyokiVenyl** [comment]
> How would this API function to retrieve the "url"? I think I'm overanalyzing how Roblox employs captchas, also called FunCaptchas, which are created by Arkose Labs. Since Roblox requests aren't monitored, I don't think you can POST requests to Gmail. Given that it requires captchas, email addresses, and other information based on the Roblox illegal content reporting system, I'm not sure how this will operate.

when you "POST" request to the url content illegal reporting (this is an example in python)
response = SESSION.post("https://www.roblox.com/illegal-content-reporting/", cookies={yourroblox_cookie, yourxcsrf_token}, headers=yourheaders, json=rawstringreason)

print(response.reason) #outputs: "challenge is required to authorize the request"

This is one notable example i've got for using a extension called HTTP-Tracker.

**Comment by Breadisfunie** [comment]
uh what tf
